Feature/equalizer
vtex/intl-equalizer pull request #1
Opened 2018-11-21 19:34 UTC by nandoacoelho

#### What is the purpose of this pull request?
- Add equalizer initial equalizer configuration
- Add error handling
- Add unit tests

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2018-11-21 19:43 UTC, klzns approved these changes

2018-11-21 19:43 UTC, klzns commented on src/configure.js
> +  const packageJson = require(`${process.cwd()}/package.json`)
```suggestion
  const packageJson = require(path.join(process.cwd(), 'package.json'))
```

2018-11-21 19:43 UTC, klzns commented on src/configure.js
> +    packageJson['intl-equalizer'].referenceLocale
Podia colocar o valor default aqui ne?

```
const referenceLocaleFromPackageJson =
  packageJson['intl-equalizer'] &&
  packageJson['intl-equalizer'].referenceLocale || 'en'
```

2018-11-21 19:43 UTC, klzns commented on src/configure.js
> +    packageJson['intl-equalizer'].localeDirectory
Idem

2018-11-21 19:43 UTC, klzns commented on src/constants.js
> +  SUCCESS: colors.yellow('✨ All keys are localized!'),
```suggestion
  SUCCESS: colors.yellow('✨ All keys are perfectly localized!'),
```

2018-11-21 19:43 UTC, klzns commented on src/equalizer.js
> +export default function equalize(languages, localesDirectory, referenceLocale) {
O que acha de receber um objeto

2018-11-21 19:50 UTC, nandoacoelho commented on src/configure.js
> +    packageJson['intl-equalizer'].referenceLocale
isso é resolvido na linha https://github.com/vtex/intl-equalizer/blob/009361a9f039de70b1722287abf81bf1e3438f33/src/configure.js#L14

2018-11-21 19:50 UTC, guilhermebruzzi requested changes
2 observações

2018-11-21 19:50 UTC, guilhermebruzzi commented on src/equalizer.test.js
> +    expect(result['en'].missingKeys.length).toBeGreaterThan(0)
Não é melhor igualar aos termos exatos do que só falar que tem que ser maior que zero?

2018-11-21 19:50 UTC, guilhermebruzzi commented on src/languages.js
> +export function getAvailableLanguages(dir) {
Essa função ao contrário da função `walk` acima não está recursiva, então imagino que pro caso do inStore que usa subfolders com locales, não funcionaria né?

2018-11-21 20:03 UTC, nandoacoelho commented on src/languages.js
> +export function getAvailableLanguages(dir) {
Por enquanto não, porém o caso do instore é de borda, a maior parte dos repos não funcionariam assim. Podemos implementar no package.json ao invés de:
```
"localeDirectory": "/src/locales/"
```
ser uma array:
```
"localeDirectories": [
    "/src/i18n/customer",
    "/src/i18n/shipping"
]
```

2018-11-21 20:05 UTC, nandoacoelho commented on src/equalizer.test.js
> +    expect(result['en'].missingKeys.length).toBeGreaterThan(0)
Como o teste descreve que deve entregar keys, pode ser `1` ou `n`, não faz muito sentido eu dizer exatamente o numero de missingKeys que retornaram.

2018-11-21 20:14 UTC, guilhermebruzzi commented on src/equalizer.test.js
> +    expect(result['en'].missingKeys.length).toBeGreaterThan(0)
Mas então faz um pra saber os termos exatos e como vc espera o formato de retorno, se não acho que os testes ficam muito soltos e podem passar mesmo tendo uma breaking change, sacou?

2018-11-21 20:15 UTC, guilhermebruzzi commented on src/languages.js
> +export function getAvailableLanguages(dir) {
Fica legal, mas não vai rolar pra gente pq ficam muitos. Acho que é melhor só ser recursivo que nem a outra função, se não quiser mexer nesse PR, eu abro um outro em seguida! :D

2018-11-21 20:16 UTC, klzns requested changes

2018-11-21 20:16 UTC, klzns commented on src/equalizer.test.js
> +      ['en', 'pt'],
Teste falhando?

2018-11-21 20:25 UTC, klzns commented on src/languages.js
> +export function getAvailableLanguages(dir) {
Ou fazer um script que usa a lib varias vezes:

```js
const modules = ['cart', 'customer', 'error'].map(module =>
  path.join(__dirname, 'src', 'i18n', module)
)

const results = modules.reduce((acc, module) => {
  const result = equalize({
    languages: getAvailableLanguages(moduleDir),
    localesDirectory: moduleDir,
    referenceLocale: 'pt',
  })

  return {
    ...result,
  }
}, {})
```

Ou a feature do seu PR fazer isso quando passado uma flag.

2018-11-21 20:43 UTC, klzns approved these changes

2018-11-22 12:10 UTC, guilhermebruzzi approved these changes
LGTM

2018-11-22 14:01 UTC, merged